ProxyPass /api/forms http://127.0.0.1:3001/api/forms
ProxyPassReverse /api/forms http://127.0.0.1:3001/api/forms

<Location /api/forms>
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "expr=%{REQUEST_SCHEME}"
    Require all granted
</Location>
